### ISSUE TITLE
Error getting translations: No row with the given identifier exists: [com.openkm.dao.bean.Language#en-Au]

### ISSUE THREAD

**Issue by JaseSmith78** [openkm/document-management-system#94]
Version: 6.3.6 (build: 87d181f)
iOS 11.4.1

Error on Safari on iOS 
No error on Safari/Chrome MacOS
No error on IE on Windows server 

no errors in Catalina.out

**Comment by darkman97i** [comment]
Login directly to the administration /OpenKM/admin and check the configuration parameter "default.lang" is empty ?

In the available translations https://docs.openkm.com/kcenter/view/okm-6.3-com/language-translations.html we do not have English from Australia, if you have not created then sure you have not registered. I do not know from where is getting en-US ( might be from your browser, but should not take effect, because you choose language from OpenKM parameter ( that's why I asked you for default.lang value ) or login language select option value.

**Comment by JaseSmith78** [comment]
I did not have a value in default.lang I assume en-GB would be the most correct for me as we do not use US spelling in Australia (and we use metric and dd/mm/yyyy date format)

The mobile version is still producing the same error - I added en-AU and left if blank and that seems to work on my iPhone now

**Comment by JaseSmith78** [comment]
I copied the GB on to an AU version with the flag - attached for others

[OpenKM_6.3.6_en-AU.sql.zip](https://github.com/openkm/document-management-system/files/2320275/OpenKM_6.3.6_en-AU.sql.zip)

**Comment by darkman97i** [comment]
I have registered the file you share with us and it's working as expected. Did you registered from Administration > database or from Administration > languages ( at bottom you have option for uploading new translation ).

In case you have choosen first option, then the issue is caused by cache. Should go to Administration > Tools > Cache stats and click on top right "Reset all" button or simply restarting OpenKM.

**Comment by JaseSmith78** [comment]
The steps I followed were:
downloaded the flag file as per the instructions on https://docs.openkm.com/kcenter/view/okm-6.3-com/how-to-create-a-new-translation.html
I then pressed the green plus to create a new language - I gave the id of en-AU and the name of Australian
I then exported both the new language I created and the en-GB. I copied the definitions in to the en-AU and did a find and replace on 'en-GB' to 'en-AU' and then I used the browse and add new translation.
this is the same file as I uploaded.

**Comment by darkman97i** [comment]
Did the issue was solved or still with it?

**Comment by JaseSmith78** [comment]
I am no longer experiencing the issue - but adding a new language is only masking the issue not fixing it - I'm happy to close but its still a bug

**Comment by JaseSmith78** [comment]
This is an upgraded install - I am unsure of the original version 
I did add the en-GB to the default.lang - I have removed
I did not restart the service after adding the new language - it was not necessary when adding.
I have removed the language file, the default.lang and restated tomcat and I still get the attached 
![20180908_204352000_ios](https://user-images.githubusercontent.com/35115241/45258503-27766080-b3fc-11e8-961f-fc0c49b4fbea.png)

**Comment by JaseSmith78** [comment]
an update - I restarted and tested again, the first sign in on my iPhone worked - so I closed the page, and reopened it - and received the same error message the second time

**Comment by JaseSmith78** [comment]
I have just attempted to re-add the language file and when I click add new translation I receive
a null pointer exception 
![np](https://user-images.githubusercontent.com/35115241/45258636-26dec980-b3fe-11e8-83b7-e2d868053c2e.PNG) I have also attached the error from the Catalina.out 
[cat-out-log.txt](https://github.com/openkm/document-management-system/files/2363737/cat-out-log.txt)

**Comment by JaseSmith78** [comment]
More testing - it seems the first sign in is presenting the mobile interface, and the second is presenting a full interface (I have managed to re-add the language file by importing it as sql - the add new translation page still throws null pointer exceptions)

**Comment by darkman97i** [comment]
I have tested the current master branch compiled code in a iPad to watch the mobile version and for me it works. Anyway can you share with us the stack trace error from catalina.log file. Because althought you do not have en-AU installed the application should provide you en-GB.

**Comment by JaseSmith78** [comment]
Microsoft EDGE is also give this error
![openkm_edge](https://user-images.githubusercontent.com/35115241/52540536-3fe90d80-2dd6-11e9-9e74-b3b320a540cc.jpg)

**Comment by darkman97i** [comment]
can you upload here the catalina.log file

**Comment by JaseSmith78** [comment]
![20190212_001227000_ios](https://user-images.githubusercontent.com/35115241/52602555-dbe64800-2eae-11e9-948c-d4210d616d2b.png)
[catalina.log](https://github.com/openkm/document-management-system/files/2853541/catalina.log)

**Comment by JaseSmith78** [comment]
default.lang is not set

**Comment by darkman97i** [comment]
I suggest upgrading to the latest 6.3.8. If the error still happens, then reopen the issue and attach the catalina.log file ( I'm interested in the error in the log file, not the entire log ).
